type: DensePassageRetriever
query_embedding_model: "facebook/dpr-question_encoder-single-nq-base"
passage_embedding_model: "facebook/dpr-ctx_encoder-single-nq-base"
max_seq_len_query: 64
max_seq_len_passage: 256
batch_size: 8
use_gpu: false
embed_title: true
use_fast_tokenizers: true
