components:
  doc_embedder:
    init_parameters:
      batch_size: 32
      device:
        device: cpu
        type: single
      embedding_separator: '

        '
      meta_fields_to_embed: []
      model: sentence-transformers/all-MiniLM-L6-v2
      normalize_embeddings: false
      prefix: ''
      progress_bar: true
      suffix: ''
      token:
        env_vars:
        - HF_API_TOKEN
        strict: false
        type: env_var
    type: haystack.components.embedders.sentence_transformers_document_embedder.SentenceTransformersDocumentEmbedder
