components:
- name: Store
  params:
    host: localhost
    index: index-name
    port: 80
  type: ElasticsearchDocumentStore
- name: Retriever
  params:
    document_store: Store
    top_k: 10
  type: BM25Retriever
- name: RagRetriever
  params:
    document_store: null
    query_embedding_model: rag_query_embedding_model
    passage_embedding_model: facebook/dpr-ctx_encoder-single-nq-base
  type: DensePassageRetriever
- name: Reranker
  params:
    batch_size: 32
    model_name_or_path: cross-encoder/ms-marco-MiniLM-L-12-v2
    top_k: 10
    use_gpu: true
  type: SentenceTransformersRanker
- name: Reader
  params:
    model_name_or_path: fact_checking_model_name_or_path
    retriever: RagRetriever
    top_k: 1
    min_length: 1
    use_gpu: true
  type: RAGenerator
pipelines:
- name: my_pipeline
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reranker
  - inputs:
    - Reranker
    name: Reader
version: 1.12.2
