components:
    Retriever:
        init_parameters:
            document_store:
                init_parameters: {}
                type: haystack.document_stores.in_memory.document_store.InMemoryDocumentStore
            top_k: 10
        type: haystack.components.retrievers.in_memory.bm25_retriever.InMemoryBM25Retriever
    Reranker:
        init_parameters:
            model: cross-encoder/ms-marco-MiniLM-L-12-v2
            device:
            top_k: 3
            model_kwargs: {}
        type: haystack.components.rankers.transformers_similarity.TransformersSimilarityRanker
    Generator:
        init_parameters:
            model: philschmid/bart-large-cnn-samsum
            task: text2text-generation
            generation_kwargs:
                max_new_tokens: 200
                num_beams: 1
                early_stopping: true
                num_return_sequences: 1
            huggingface_pipeline_kwargs: {}
        type: haystack.components.generators.hugging_face_local.HuggingFaceLocalGenerator
    PromptBuilder:
        init_parameters:
            template: |
                {% for doc in documents %}
                    {{ doc.content }}
                {% endfor %}
        type: haystack.components.builders.prompt_builder.PromptBuilder
connections:
    - receiver: Reranker.documents
      sender: Retriever
    - receiver: PromptBuilder.documents
      sender: Reranker
    - receiver: Generator
      sender: PromptBuilder
